name: My First Github Actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #cloning the repo
      - uses: actions/setup-node@v2 #install node
        with:
          node-version: 14.x
      - name: Install node_modules
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Setup Completed
        run: echo "Setup Completed"
